apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2019-01-15T15:59:18Z
  generation: 15
  labels:
    app: nexus
    template: nexus3-persistent-template
  name: nexus
  namespace: nexus
  resourceVersion: "4722960"
  selfLink: /apis/apps.openshift.io/v1/namespaces/nexus/deploymentconfigs/nexus
  uid: 83e0df28-18de-11e9-8365-0050569fef90
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: nexus
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      post:
        execNewPod:
          command:
          - /bin/bash
          - -c
          - export HTTP_PROXY=http://ya01578:rhCGD!POC01@10.11.18.11:8080; export
            HTTPS_PROXY=http://ya01578:rhCGD!POC01@10.11.18.11:8080; export NO_PROXY=.cluster,.cluster.local,.grupocgd.com,.local,.svc,10.11.203.50,127.0.0.1,169.254.169.254,172.30.0.1,bpmconsole.grupocgd.com,ldc6001bpm01.grupocgd.com,ldc6001bpm02.grupocgd.com,ldc6001bpm03.grupocgd.com,ldc6001bpm05.grupocgd.com,ldc6001bpm06.grupocgd.com,localhost,172.30.0.0/16,10.128.0.0/14,ldc6001bpm01,,ldc6001bpm02,,ldc6001bpm03,,ldc6001bpm05,,ldc6001bpm06;
            curl -o /tmp/nexus-functions  https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/scripts/nexus-functions;
            ls -la /tmp; source /tmp/nexus-functions; add_nexus3_redhat_repos admin
            admin123 http://nexus:8081
          containerName: nexus
        failurePolicy: Abort
      timeoutSeconds: 1200
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: nexus
    spec:
      containers:
      - env:
        - name: CONTEXT_PATH
          value: /
        image: docker.io/sonatype/nexus3@sha256:b8498fbb371b4bf20073a4422721677c832ef854578e957a4b0f4aa4870972d1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - echo
            - ok
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nexus
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pv
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nexus
      from:
        kind: ImageStreamTag
        name: nexus:3.6.0
        namespace: nexus
      lastTriggeredImage: docker.io/sonatype/nexus3@sha256:b8498fbb371b4bf20073a4422721677c832ef854578e957a4b0f4aa4870972d1
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-11T11:54:19Z
    lastUpdateTime: 2019-02-11T11:54:19Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-11T11:52:43Z
    lastUpdateTime: 2019-02-11T11:54:39Z
    message: replication controller "nexus-9" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: Manual
    message: manual change
  latestVersion: 9
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
